In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
scalar.shape, vector.shape

(torch.Size([]), torch.Size([2]))

In [13]:
MATRIX = torch.tensor([[7,8],
                    [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX[1][1]

tensor(10)

In [28]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [19]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.shape, TENSOR.ndim

(torch.Size([1, 3, 3]), 3)

### Random TENOSRS