In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
scalar.shape, vector.shape

(torch.Size([]), torch.Size([2]))

In [13]:
MATRIX = torch.tensor([[7,8],
                    [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX[1][1]

tensor(10)

In [28]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [19]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.shape, TENSOR.ndim

(torch.Size([1, 3, 3]), 3)

### Random TENOSRS

In [32]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4854, 0.9232, 0.2513, 0.0404],
        [0.6797, 0.6704, 0.5848, 0.1858],
        [0.7752, 0.3774, 0.4230, 0.8524]])

In [33]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

In [34]:
random_tensor = torch.rand(1,2,3)
random_tensor

tensor([[[0.3702, 0.5703, 0.0283],
         [0.6152, 0.1824, 0.7391]]])

In [35]:
random_tensor.shape, random_tensor.ndim

(torch.Size([1, 2, 3]), 3)

In [40]:
random_image_tenosr = torch.rand(size=(3,224,224)) # height, width, colour channels
random_image_tenosr

tensor([[[2.1173e-01, 8.0827e-01, 3.4111e-01,  ..., 8.2943e-01,
          8.2478e-01, 2.8447e-01],
         [8.0548e-01, 6.5339e-01, 9.0049e-01,  ..., 5.7808e-01,
          5.1062e-01, 3.1850e-01],
         [4.6719e-01, 1.5406e-02, 5.6675e-01,  ..., 2.3622e-01,
          2.5505e-01, 8.6042e-02],
         ...,
         [8.4564e-01, 7.1587e-01, 3.7637e-01,  ..., 8.8908e-01,
          5.7946e-01, 8.9330e-01],
         [5.9323e-01, 8.9474e-01, 2.8408e-01,  ..., 7.7285e-01,
          1.2462e-01, 2.1593e-01],
         [1.0559e-02, 8.5743e-02, 4.3497e-01,  ..., 5.7231e-01,
          1.7203e-01, 3.8616e-01]],

        [[4.2363e-01, 2.5469e-01, 7.2407e-01,  ..., 3.4120e-01,
          9.9753e-01, 1.4064e-01],
         [6.2143e-01, 3.8434e-01, 4.2264e-01,  ..., 3.6748e-01,
          1.2600e-01, 1.1553e-02],
         [2.2564e-01, 8.2560e-01, 2.0885e-01,  ..., 3.2274e-01,
          2.3908e-02, 1.5414e-01],
         ...,
         [7.7979e-01, 6.4322e-01, 7.0057e-01,  ..., 4.7980e-01,
          6.629

In [47]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

### range and like tensors

In [ ]:
one_to_ten = torch.arange(start=1,end=100,step=10)
one_to_ten

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
one_to_ten.shape, one_to_ten.ndim

(torch.Size([10]), 1)

In [55]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [56]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
ten_ones = torch.ones_like(input=one_to_ten)

In [59]:
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Datatypes

In [65]:
int64 = torch.tensor([1,2])

In [66]:
int64.dtype

torch.int64

In [67]:
float32 = torch.tensor([1.2,2.2])
float32.dtype

torch.float32

In [70]:
float64 = torch.tensor([1.3,2.4],dtype=torch.float64)
float64

tensor([1.3000, 2.4000], dtype=torch.float64)

In [71]:
float64.shape, float64.ndim

(torch.Size([2]), 1)

In [72]:
float64.device

device(type='cpu')

In [73]:
float64.shape, float64.size()

(torch.Size([2]), torch.Size([2]))

#### TENSOR OPERATIONS 

In [76]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [77]:
tensor =  tensor*3
tensor

tensor([33, 36, 39])

In [79]:
tensor =  tensor-10
tensor

tensor([23, 26, 29])

In [80]:
tensor = tensor/3
tensor

tensor([7.6667, 8.6667, 9.6667])

In [82]:
tensor = torch.mul(tensor,10)
tensor

tensor([76.6667, 86.6667, 96.6667])

In [83]:
tensor = tensor.int()
tensor

tensor([76, 86, 96], dtype=torch.int32)