In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
scalar.shape, vector.shape

(torch.Size([]), torch.Size([2]))

In [13]:
MATRIX = torch.tensor([[7,8],
                    [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX[1][1]

tensor(10)

In [28]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [19]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.shape, TENSOR.ndim

(torch.Size([1, 3, 3]), 3)

### Random TENOSRS

In [32]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4854, 0.9232, 0.2513, 0.0404],
        [0.6797, 0.6704, 0.5848, 0.1858],
        [0.7752, 0.3774, 0.4230, 0.8524]])

In [33]:
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 4]), 2)

In [34]:
random_tensor = torch.rand(1,2,3)
random_tensor

tensor([[[0.3702, 0.5703, 0.0283],
         [0.6152, 0.1824, 0.7391]]])

In [35]:
random_tensor.shape, random_tensor.ndim

(torch.Size([1, 2, 3]), 3)

In [40]:
random_image_tenosr = torch.rand(size=(3,224,224)) # height, width, colour channels
random_image_tenosr

tensor([[[2.1173e-01, 8.0827e-01, 3.4111e-01,  ..., 8.2943e-01,
          8.2478e-01, 2.8447e-01],
         [8.0548e-01, 6.5339e-01, 9.0049e-01,  ..., 5.7808e-01,
          5.1062e-01, 3.1850e-01],
         [4.6719e-01, 1.5406e-02, 5.6675e-01,  ..., 2.3622e-01,
          2.5505e-01, 8.6042e-02],
         ...,
         [8.4564e-01, 7.1587e-01, 3.7637e-01,  ..., 8.8908e-01,
          5.7946e-01, 8.9330e-01],
         [5.9323e-01, 8.9474e-01, 2.8408e-01,  ..., 7.7285e-01,
          1.2462e-01, 2.1593e-01],
         [1.0559e-02, 8.5743e-02, 4.3497e-01,  ..., 5.7231e-01,
          1.7203e-01, 3.8616e-01]],

        [[4.2363e-01, 2.5469e-01, 7.2407e-01,  ..., 3.4120e-01,
          9.9753e-01, 1.4064e-01],
         [6.2143e-01, 3.8434e-01, 4.2264e-01,  ..., 3.6748e-01,
          1.2600e-01, 1.1553e-02],
         [2.2564e-01, 8.2560e-01, 2.0885e-01,  ..., 3.2274e-01,
          2.3908e-02, 1.5414e-01],
         ...,
         [7.7979e-01, 6.4322e-01, 7.0057e-01,  ..., 4.7980e-01,
          6.629

In [47]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

### range and like tensors

In [ ]:
one_to_ten = torch.arange(start=1,end=100,step=10)
one_to_ten

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
one_to_ten.shape, one_to_ten.ndim

(torch.Size([10]), 1)

In [55]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [56]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
ten_ones = torch.ones_like(input=one_to_ten)

In [59]:
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Datatypes

In [65]:
int64 = torch.tensor([1,2])

In [66]:
int64.dtype

torch.int64

In [67]:
float32 = torch.tensor([1.2,2.2])
float32.dtype

torch.float32

In [70]:
float64 = torch.tensor([1.3,2.4],dtype=torch.float64)
float64

tensor([1.3000, 2.4000], dtype=torch.float64)

In [71]:
float64.shape, float64.ndim

(torch.Size([2]), 1)

In [72]:
float64.device

device(type='cpu')

In [73]:
float64.shape, float64.size()

(torch.Size([2]), torch.Size([2]))

#### TENSOR OPERATIONS 

In [76]:
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [77]:
tensor =  tensor*3
tensor

tensor([33, 36, 39])

In [79]:
tensor =  tensor-10
tensor

tensor([23, 26, 29])

In [80]:
tensor = tensor/3
tensor

tensor([7.6667, 8.6667, 9.6667])

In [82]:
tensor = torch.mul(tensor,10)
tensor

tensor([76.6667, 86.6667, 96.6667])

In [83]:
tensor = tensor.int()
tensor

tensor([76, 86, 96], dtype=torch.int32)

#### multiplications or dot proctuct
the inner dims must match and the result is the outer dims

In [96]:
a  = torch.matmul(torch.rand(3,2),torch.rand(2,3))
a, a.shape

(tensor([[0.1394, 0.3153, 0.4161],
         [0.1436, 0.2139, 0.3358],
         [0.0341, 0.2433, 0.2408]]),
 torch.Size([3, 3]))

In [97]:
b  = torch.matmul(torch.rand(4,5),torch.rand(5,4))
b, b.shape

(tensor([[1.0413, 1.0808, 1.1787, 1.0732],
         [0.8808, 0.6197, 0.9872, 0.6031],
         [1.3412, 1.0370, 1.7296, 1.2304],
         [1.1913, 1.1448, 1.5375, 1.5007]]),
 torch.Size([4, 4]))

In [94]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [89]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])

In [90]:
tenosr3 = torch.matmul(tensor1,tensor2)
tenosr3

tensor(32)

In [91]:
tenosr3 = torch.mul(tensor1,tensor2)
tenosr3

tensor([ 4, 10, 18])

mat mul does the matrix mul and the mul does the straight mul
torch.matmul and torch.mm are same

In [98]:
c  = torch.mm(torch.rand(3,2),torch.rand(2,3))
c, c.shape

(tensor([[0.9168, 0.2686, 0.7328],
         [0.2221, 0.4053, 0.4643],
         [0.7859, 0.6087, 0.9472]]),
 torch.Size([3, 3]))

In [101]:
tensor1 = torch.rand(3,4)
tensor2 = torch.rand(3,4)

In [102]:
torch.mm(tensor1, tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [103]:
tensor2.shape

torch.Size([3, 4])

In [ ]:
tensor2 = tensor2.T # apply transpose

In [107]:
tensor2.shape

torch.Size([4, 3])

In [108]:
torch.mm(tensor1, tensor2)

tensor([[0.7053, 0.3436, 0.8011],
        [1.0037, 1.0414, 1.5274],
        [0.6716, 1.1599, 0.9599]])

##### tensor aggergation - min,max,sum , etc

In [113]:
x = torch.arange(0,100,20)
x

tensor([ 0, 20, 40, 60, 80])

In [114]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [116]:
torch.max(x), x .max()

(tensor(80), tensor(80))

In [117]:
torch.sum(x), x.sum()

(tensor(200), tensor(200))

In [118]:
torch.mean(x) , x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [121]:
y = x.type(torch.float32)
torch.mean(y), y.mean()

(tensor(40.), tensor(40.))

##### args max and args min

In [123]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [126]:
torch.argmax(x), x.argmax()

(tensor(4), tensor(4))

##### reshaping, stacking squeezing, unsqueezing, permute

In [133]:
x = torch.arange(1.,11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [135]:
x_reshape = x.reshape(1,10)
x_reshape , x_reshape.shape, x_reshape.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]),
 2)

In [131]:
x_reshape = x.reshape(9,1)
x_reshape , x_reshape.shape, x_reshape.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [132]:
x_reshape = x.reshape(1,9,1)
x_reshape , x_reshape.shape, x_reshape.ndim

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]),
 3)

In [136]:
x_reshape = x.reshape(5,2)
x_reshape , x_reshape.shape, x_reshape.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 2)

the reshaped tensor when multiplied need to the actuatl shape of the original tenosr

In [139]:
x = torch.arange(1.,10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [141]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

view points to the orginal tensor so changing z changes the x they share the same memoery

In [144]:
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]),
 2)

In [150]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]),
 2)

In [151]:
tensor1 = torch.rand(1,3,4)

In [152]:
tensor1

tensor([[[0.4034, 0.5700, 0.3315, 0.1233],
         [0.1943, 0.0513, 0.3592, 0.7576],
         [0.6542, 0.9819, 0.0374, 0.4396]]])

In [153]:
tensor1.shape, tensor1.ndim

(torch.Size([1, 3, 4]), 3)

In [155]:
tensor1.squeezed = torch.squeeze(tensor1)
tensor1.squeezed, tensor1.squeezed.shape, tensor1.squeezed.ndim

(tensor([[0.4034, 0.5700, 0.3315, 0.1233],
         [0.1943, 0.0513, 0.3592, 0.7576],
         [0.6542, 0.9819, 0.0374, 0.4396]]),
 torch.Size([3, 4]),
 2)

In [165]:
tensor1.unsqueezed = torch.unsqueeze(tensor1.squeezed ,dim=2)
tensor1.unsqueezed, tensor1.unsqueezed.shape, tensor1.unsqueezed.ndim

(tensor([[[0.4034],
          [0.5700],
          [0.3315],
          [0.1233]],
 
         [[0.1943],
          [0.0513],
          [0.3592],
          [0.7576]],
 
         [[0.6542],
          [0.9819],
          [0.0374],
          [0.4396]]]),
 torch.Size([3, 4, 1]),
 3)

In [174]:
x_squeezed = tensor1.squeeze()
x_squeezed, x_squeezed.shape, x_squeezed.ndim

(tensor([[0.4034, 0.5700, 0.3315, 0.1233],
         [0.1943, 0.0513, 0.3592, 0.7576],
         [0.6542, 0.9819, 0.0374, 0.4396]]),
 torch.Size([3, 4]),
 2)

permute is to change the orders in tensors

In [182]:
i = torch.rand(size=(224,224,3)) 
i.shape, i.ndim

(torch.Size([224, 224, 3]), 3)

In [183]:
i = i.permute(2,0,1)
i.shape, i.ndim

(torch.Size([3, 224, 224]), 3)

In [184]:
i = i.permute(2,0,1)
i.shape, i.ndim

(torch.Size([224, 3, 224]), 3)

In [192]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [193]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [194]:
x[0][0]

tensor([1, 2, 3])

In [195]:
x[0][0][0]

tensor(1)

In [198]:
x[0,0,0]

tensor(1)

In [206]:
x[:,:,1]

tensor([[2, 5, 8]])

In [208]:
x[:,1,1]

tensor([5])

### numpy

In [209]:
import numpy as np

In [210]:
array = np.arange(1.0,8.0)
array.dtype , array.shape

(dtype('float64'), (7,))

In [211]:
array = torch.from_numpy(array)
array.dtype , array.shape

(torch.float64, torch.Size([7]))

In [216]:
tensor = torch.ones(7)
tensor.dtype

torch.float32

In [217]:
numpy_tensor = torch.Tensor.numpy(tensor)
numpy_tensor.dtype

dtype('float32')

In [218]:
tensor1 = torch.ones(7)
tensor1.dtype

torch.float32

In [219]:
numpy_tensor1 = tensor1.numpy()
numpy_tensor1.dtype

dtype('float32')

### Reproducbility to make the random ness same everytime

In [228]:
a = torch.rand(3,3)

In [229]:
b = torch.rand(3,3)

In [230]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [231]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [232]:
c = torch.rand(3,3)

In [233]:
torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,3)

In [234]:
c == d

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])